[platformio]
default_envs = nodemcuv2

[env]
; Impostazioni globali per l'ambiente
platform = espressif8266
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
monitor_dtr = 0
monitor_rts = 0

; Librerie esterne da scaricare (Servo omessa perché già inclusa nel core)
lib_deps =
	adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
	miguelbalboa/MFRC522 @ ^1.4.11

[env:nodemcuv2]
; Impostazioni specifiche per la board NodeMCU
board = nodemcuv2
upload_speed = 115200