[platformio]
default_envs = nodemcuv2

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
monitor_dtr = 0
monitor_rts = 0
lib_deps =
	adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
	miguelbalboa/MFRC522 @ ^1.4.11
	robtillaart/I2CKeyPad @ ^0.3.3

[env:nodemcuv2]
board = nodemcuv2
upload_speed = 115200