[platformio]
default_envs = nodemcuv2

[env]
; Configurazione hardware e framework per ESP8266
platform = espressif8266
framework = arduino

; Impostazioni di comunicazione seriale (Allineate alla tua COM4)
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

; Disabilitazione segnali di controllo per prevenire riavvii hardware indesiderati
monitor_dtr = 0
monitor_rts = 0

; Gestore delle dipendenze di terze parti
lib_deps =
; Sensore biometrico AS608
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0

; Stack di comunicazione SPI per lettore RFID MFRC522
    miguelbalboa/MFRC522 @ ^1.4.11

; Interfaccia I2C per tastierino a matrice tramite PCF8574
    robtillaart/I2CKeyPad @ ^0.3.3

; Core grafico vettoriale e driver specifico per pannello OLED SSD1306
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit SSD1306 @ ^2.5.7

; Client MQTT per pubblicazione e sottoscrizione messaggi sul broker
    knolleary/PubSubClient @ ^2.8

[env:nodemcuv2]
; Impostazioni specifiche per la board NodeMCU v2
board = nodemcuv2
upload_speed = 115200